### ISSUE TITLE
Plugin doesn't work

### ISSUE THREAD

**Issue by welnanick** [bomanimc/gitrocket#1]
I am using Hyper 1.4.2 (stable) and I tried to add this plugin, but when I push to my remote nothing happens. I have the following plugins loaded:
* hypertheme (0.1.0),
* hyper-solarized-dark (0.1.3),
* hyper-nobold (1.0.0),
* hyperline (0.6.1),
* hyperfull (2.0.1),
* hyper-quit (1.0.2),
* gitrocket (1.0.3)

I am on macOS Sierra 10.12.6

**Comment by staffanmowitz** [comment]
I can't get it to work either!

I'm running Hyper 1.4.2 (stable) and I have tried both with and without other plugins.

**Comment by brooksa321** [comment]
+1 Running Arch Linux Hyper 1.4.2(stable)

**Comment by bomanimc** [comment]
Hi all @brooksa321 @staffanmowitz @welnanick. Thanks for leaving issues and sorry about the lateness in responding. I'm not sure the best way to debug this issue since I can't repro using 1.4.2 on macOS 10.12.2, but we can discuss a few things that could potentially cause issue.

Can you try typing in `To .git` directly into your terminal and entering it? The command will fail, but this should be enough to trigger the regex here to work. 

Gitrocket checks new lines in the terminal using this regex match: https://github.com/bomanimc/gitrocket/blob/master/src/GitRocketTerminal.jsx#L11

When I push to remote I get a message like the one attached. This was inspiration to use this method:
<img width="329" alt="screen shot 2017-09-23 at 10 13 36 am" src="https://user-images.githubusercontent.com/6589909/30773890-0a874ad4-a048-11e7-889b-21535fe58607.png">

When you push to remote, what message do you get? I wonder if that could be a source of the issue.

**Comment by brooksa321** [comment]
@bomanimc @staffanmowitz @welnanick 
Yup, that's it, The regex isn't catching if you're pushing over HTTPS:
![gitrocketwrong](https://user-images.githubusercontent.com/9658949/30778297-0ff007f6-a0a0-11e7-8f2f-34abe85bd25d.png)

but it works fine if you do it over ssh:
![gitrocketright](https://user-images.githubusercontent.com/9658949/30778301-2f96be6a-a0a0-11e7-8741-88aba9958e2f.png)

**Comment by bomanimc** [comment]
Glad we caught that. I'll push a fix soon!

**Comment by bomanimc** [comment]
Just updated the package to version 1.0.4, which should include a fix for this issue. Please reopen if you continue to have issues after updating!

**Comment by welnanick** [comment]
Everything works now!

Its odd, because I was pushing over ssh, but my remote has the format `ssh://*url*` for the address, which is probably why it wasn't working before. But it is now!

**Comment by panmona** [comment]
I currently have the same issue :/
I found that when I open a new tab and try the `To .git` "command" the rocket appears the first time but when I do that again it won't.
Can you reproduce that?
(Using Hyper2 with Powershell on Win10)

**Comment by rdbartram** [comment]
@maracuja-juice it displays the animation only when it pulls something from remote. Hence it will only show the 'first time'. Everytime there is new info in remote, it should display

**Comment by panmona** [comment]
@rdbartram It should not display the animation `when it pulls something from remote`
